-------------------------------------
---------- CREATE ROLE --------------
-------------------------------------

CREATE ROLE PROGRAMMER_ROLE;
CREATE ROLE USER_ROLE;
CREATE ROLE MANAGER_ROLE;
-------------- PROGRAMMER_ROLE ------------------
GRANT ALL PRIVILEGES ON DATABASE "BD_MUSIC" TO PROGRAMMER_ROLE;
GRANT CONNECT ON DATABASE "BD_MUSIC"  TO PROGRAMMER_ROLE;

GRANT ALL ON TABLESPACE TS_USER TO PROGRAMMER_ROLE;
GRANT ALL ON TABLESPACE TS_TRACK TO PROGRAMMER_ROLE;
GRANT ALL ON TABLESPACE TS_PLAYLIST TO PROGRAMMER_ROLE;
GRANT ALL ON TABLESPACE TS_LIBRARY TO PROGRAMMER_ROLE;
-------------- USER_ROLE ------------------
GRANT EXECUTE ON FUNCTION REGISTER TO USER_ROLE;
GRANT EXECUTE ON FUNCTION LOGIN TO USER_ROLE;
GRANT EXECUTE ON FUNCTION ADDTRACK TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE ADD_RATING TO USER_ROLE;
GRANT EXECUTE ON FUNCTION CREATEPLAYLIST TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE ADD_TRACK_TO_PLAYLIST TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE ADD_TRACK_TO_LIBRARY TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE ADD_TRACK_TO_LIBRARY TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_USER TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_USER_PASSWORD TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_TRACK TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_PLAYLIST TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE DELETE_TRACK TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE REMOVE_TRACK_FROM_PLAYLIST TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE DELETE_PLAYLIST TO USER_ROLE;
GRANT EXECUTE ON PROCEDURE DELETE_TRACK_FROM_LIBRARY TO USER_ROLE;
GRANT EXECUTE ON FUNCTION  GETUSERBYID TO USER_ROLE;
GRANT EXECUTE ON FUNCTION  SEARCH_TRACK_BY_TITLE_OR_USER_NAME TO USER_ROLE;	
GRANT SELECT, INSERT, UPDATE ON TABLE USERS TO USER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE TRACK TO USER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE RATING TO USER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_TRACK TO USER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PLAYLIST TO USER_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE LIBRARY_USER TO USER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE PLAYLIST_TRACKS TO USER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE USERS_USER_ID_SEQ TO USER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE TRACK_TRACK_ID_SEQ TO USER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE RATING_RATING_ID_SEQ TO USER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE PLAYLIST_PLAYLIST_ID_SEQ TO USER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE LIBRARY_USER_ID_SEQ TO USER_ROLE;

-------------- MANAGER_ROLE ------------------
GRANT EXECUTE ON FUNCTION REGISTER TO MANAGER_ROLE;
GRANT EXECUTE ON FUNCTION  GETUSERBYID TO MANAGER_ROLE;
GRANT EXECUTE ON FUNCTION  SEARCH_TRACK_BY_TITLE_OR_USER_NAME TO MANAGER_ROLE;	
GRANT EXECUTE ON FUNCTION ADDTRACK TO MANAGER_ROLE;
GRANT EXECUTE ON FUNCTION GETTRACKS TO MANAGER_ROLE;
GRANT EXECUTE ON FUNCTION GETUSERS TO MANAGER_ROLE;
GRANT EXECUTE ON FUNCTION GETTRACKBYID TO MANAGER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_USER TO MANAGER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_USER_PASSWORD TO MANAGER_ROLE;
GRANT EXECUTE ON PROCEDURE DELETE_TRACK TO MANAGER_ROLE;
GRANT EXECUTE ON PROCEDURE DELETE_USER TO MANAGER_ROLE;
GRANT EXECUTE ON PROCEDURE UPDATE_TRACK TO MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE ON TABLE USERS TO MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE TRACK TO MANAGER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE USER_TRACK TO MANAGER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE USERS_USER_ID_SEQ TO MANAGER_ROLE;
GRANT USAGE, SELECT ON SEQUENCE TRACK_TRACK_ID_SEQ TO MANAGER_ROLE;

-------------------------------------
---------- CREATE USER --------------
-------------------------------------
CREATE USER PROGRAMMER_1 PASSWORD '123';
GRANT PROGRAMMER_ROLE TO PROGRAMMER_1;

CREATE USER USER_1 WITH PASSWORD '123';
GRANT USER_ROLE TO USER_1;

CREATE USER MANAGER_1 WITH PASSWORD '123';
GRANT MANAGER_ROLE TO MANAGER_1;